travis:
  secure:
    BINSTAR_TOKEN: P4d5DhTLsNsYJr8JWutwSKszpALkrJvPd87h7uItuDU6Cp0JV7ssa0+WkDga6qdCcp/LbAN2xCiFT5LpoABZMPWOrDatDa4fiHjhn2VMo9v6+NP4r7NLmw87W94+g6zwnBS58q3SrzkCpLwtSChK5m4TzL6ra7OMCf3MtOjkCkLBVBDlWgkvvQmrLcpDlWedEaw768UKMl8jwdoARwTVBsHciCEMysUgiP4UG15BF+dXGT5K/17VGeEwMJJhwqd+C8pv6s8IJAq+7y+VXhYBwa+35YXTFHGat8S+uru3MwKkhhXQ17uzGbB87cmRgi3SR3wKQJQA/cYGY3b4gtgYfmRwEJS+ZN5YlJkVQeFpG/yDpwC+6zFCtKquZ1NmyvuR+NuYJjPCCjO1s6Se3LUZR4NTkjILRTh2x1Dbro9xXfXKBqSwaYAcaldO30a1GARy9sLdjeZq7uhn3MeaPCrtWRV+/fx+rXtTOXB1BWrDx0Zgc2AYtjysiOyLB0lkjNsk+VCzinP7PkEfhvCBWLF58dvROwKPm97c09rYJLZOu/qutRWxNSaKFIcpzFlRYTOkVY9vJsFHnFicnVIg3gncBn7nc8hFgjwVUXRFqZOHka38agEQxOG1+QP9evHVXJ2i2gU2Rr8jzC9NCgXxs2UOS1IYWGFKANCnyvEoa4CGRk8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
